### ISSUE TITLE
✨ [FEATURE] UnitOfWork --> EfCore Transactions and Rollbacks?

### ISSUE THREAD

**Issue by jeffward01** [furkandeveloper/EasyRepository.EFCore#20]
## Summary

I am not sure if there is a reason why this is not implemented, perhaps you have done some tests and its not as simple as it looks.

Is there any reason why `Transactions` and `Rollback` is not implemented?

Is this something that you'd like me to add?

Is there any particular feature or way you would like this to be implemented? 

### Reading
* https://learn.microsoft.com/en-us/ef/core/saving/transactions
* https://learn.microsoft.com/en-us/ef/ef6/saving/transactions

**Comment by furkandeveloper** [comment]
UnitOfWork works with all or nothing logic.

Managing transactions is one method. However, no update or add method will be committed to the database without savechange running.
Users have to call UnitOfWork.Repository.Complete method because savechanges will not work without the Complete method in scope.

Supports EF Core Change Tracker feature. Tries to apply all changes to the context. If he gets an error on any of them, he can't perform any action anyway.

**Comment by jeffward01** [comment]
I respect that this is closed, and your explanation makes sense.

I am curious as to why Microsoft has a `TransactionScope` and a `Rollback` ability in this case?  

I think this is more of an EfCore question, if you have time can you help me understand why this is the case?

**Comment by furkandeveloper** [comment]
This resource will be useful to you.

https://stackoverflow.com/questions/50844828/ef-db-savechanges-vs-dbtransaction-commit
